<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Homes extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Homes_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('homes/homes_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Homes_model->json();
    }

    public function read($id) 
    {
        $row = $this->Homes_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'created_at' => $row->created_at,
		'updated_at' => $row->updated_at,
	    );
            $this->load->view('homes/homes_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('homes'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('homes/create_action'),
	    'id' => set_value('id'),
	    'created_at' => set_value('created_at'),
	    'updated_at' => set_value('updated_at'),
	);
        $this->load->view('homes/homes_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'created_at' => $this->input->post('created_at',TRUE),
		'updated_at' => $this->input->post('updated_at',TRUE),
	    );

            $this->Homes_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('homes'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Homes_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('homes/update_action'),
		'id' => set_value('id', $row->id),
		'created_at' => set_value('created_at', $row->created_at),
		'updated_at' => set_value('updated_at', $row->updated_at),
	    );
            $this->load->view('homes/homes_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('homes'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'created_at' => $this->input->post('created_at',TRUE),
		'updated_at' => $this->input->post('updated_at',TRUE),
	    );

            $this->Homes_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('homes'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Homes_model->get_by_id($id);

        if ($row) {
            $this->Homes_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('homes'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('homes'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('created_at', 'created at', 'trim|required');
	$this->form_validation->set_rules('updated_at', 'updated at', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Homes.php */
/* Location: ./application/controllers/Homes.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
