<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jabatan_fungsional_syarat_kelompok extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Jabatan_fungsional_syarat_kelompok_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('jabatan_fungsional_syarat_kelompok/jabatan_fungsional_syarat_kelompok_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Jabatan_fungsional_syarat_kelompok_model->json();
    }

    public function read($id) 
    {
        $row = $this->Jabatan_fungsional_syarat_kelompok_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_judul' => $row->id_judul,
		'id_syarat' => $row->id_syarat,
	    );
            $this->load->view('jabatan_fungsional_syarat_kelompok/jabatan_fungsional_syarat_kelompok_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_fungsional_syarat_kelompok'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jabatan_fungsional_syarat_kelompok/create_action'),
	    'id' => set_value('id'),
	    'id_judul' => set_value('id_judul'),
	    'id_syarat' => set_value('id_syarat'),
	);
        $this->load->view('jabatan_fungsional_syarat_kelompok/jabatan_fungsional_syarat_kelompok_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_judul' => $this->input->post('id_judul',TRUE),
		'id_syarat' => $this->input->post('id_syarat',TRUE),
	    );

            $this->Jabatan_fungsional_syarat_kelompok_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jabatan_fungsional_syarat_kelompok'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jabatan_fungsional_syarat_kelompok_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jabatan_fungsional_syarat_kelompok/update_action'),
		'id' => set_value('id', $row->id),
		'id_judul' => set_value('id_judul', $row->id_judul),
		'id_syarat' => set_value('id_syarat', $row->id_syarat),
	    );
            $this->load->view('jabatan_fungsional_syarat_kelompok/jabatan_fungsional_syarat_kelompok_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_fungsional_syarat_kelompok'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_judul' => $this->input->post('id_judul',TRUE),
		'id_syarat' => $this->input->post('id_syarat',TRUE),
	    );

            $this->Jabatan_fungsional_syarat_kelompok_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jabatan_fungsional_syarat_kelompok'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jabatan_fungsional_syarat_kelompok_model->get_by_id($id);

        if ($row) {
            $this->Jabatan_fungsional_syarat_kelompok_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jabatan_fungsional_syarat_kelompok'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_fungsional_syarat_kelompok'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_judul', 'id judul', 'trim|required');
	$this->form_validation->set_rules('id_syarat', 'id syarat', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jabatan_fungsional_syarat_kelompok.php */
/* Location: ./application/controllers/Jabatan_fungsional_syarat_kelompok.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
