<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jabatan_opd extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Jabatan_opd_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('jabatan_opd/jabatan_opd_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Jabatan_opd_model->json();
    }

    public function read($id) 
    {
        $row = $this->Jabatan_opd_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_jabatan' => $row->id_jabatan,
		'id_jabatan_atas' => $row->id_jabatan_atas,
		'id_opd' => $row->id_opd,
	    );
            $this->load->view('jabatan_opd/jabatan_opd_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_opd'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jabatan_opd/create_action'),
	    'id' => set_value('id'),
	    'id_jabatan' => set_value('id_jabatan'),
	    'id_jabatan_atas' => set_value('id_jabatan_atas'),
	    'id_opd' => set_value('id_opd'),
	);
        $this->load->view('jabatan_opd/jabatan_opd_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_jabatan' => $this->input->post('id_jabatan',TRUE),
		'id_jabatan_atas' => $this->input->post('id_jabatan_atas',TRUE),
		'id_opd' => $this->input->post('id_opd',TRUE),
	    );

            $this->Jabatan_opd_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jabatan_opd'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jabatan_opd_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jabatan_opd/update_action'),
		'id' => set_value('id', $row->id),
		'id_jabatan' => set_value('id_jabatan', $row->id_jabatan),
		'id_jabatan_atas' => set_value('id_jabatan_atas', $row->id_jabatan_atas),
		'id_opd' => set_value('id_opd', $row->id_opd),
	    );
            $this->load->view('jabatan_opd/jabatan_opd_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_opd'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_jabatan' => $this->input->post('id_jabatan',TRUE),
		'id_jabatan_atas' => $this->input->post('id_jabatan_atas',TRUE),
		'id_opd' => $this->input->post('id_opd',TRUE),
	    );

            $this->Jabatan_opd_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jabatan_opd'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jabatan_opd_model->get_by_id($id);

        if ($row) {
            $this->Jabatan_opd_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jabatan_opd'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_opd'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_jabatan', 'id jabatan', 'trim|required');
	$this->form_validation->set_rules('id_jabatan_atas', 'id jabatan atas', 'trim|required');
	$this->form_validation->set_rules('id_opd', 'id opd', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jabatan_opd.php */
/* Location: ./application/controllers/Jabatan_opd.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
