<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jabatan_pelaksana_kelompok extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Jabatan_pelaksana_kelompok_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('jabatan_pelaksana_kelompok/jabatan_pelaksana_kelompok_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Jabatan_pelaksana_kelompok_model->json();
    }

    public function read($id) 
    {
        $row = $this->Jabatan_pelaksana_kelompok_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nama_kelompok' => $row->nama_kelompok,
		'id_kelas' => $row->id_kelas,
	    );
            $this->load->view('jabatan_pelaksana_kelompok/jabatan_pelaksana_kelompok_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_pelaksana_kelompok'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jabatan_pelaksana_kelompok/create_action'),
	    'id' => set_value('id'),
	    'nama_kelompok' => set_value('nama_kelompok'),
	    'id_kelas' => set_value('id_kelas'),
	);
        $this->load->view('jabatan_pelaksana_kelompok/jabatan_pelaksana_kelompok_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kelompok' => $this->input->post('nama_kelompok',TRUE),
		'id_kelas' => $this->input->post('id_kelas',TRUE),
	    );

            $this->Jabatan_pelaksana_kelompok_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jabatan_pelaksana_kelompok'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jabatan_pelaksana_kelompok_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jabatan_pelaksana_kelompok/update_action'),
		'id' => set_value('id', $row->id),
		'nama_kelompok' => set_value('nama_kelompok', $row->nama_kelompok),
		'id_kelas' => set_value('id_kelas', $row->id_kelas),
	    );
            $this->load->view('jabatan_pelaksana_kelompok/jabatan_pelaksana_kelompok_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_pelaksana_kelompok'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nama_kelompok' => $this->input->post('nama_kelompok',TRUE),
		'id_kelas' => $this->input->post('id_kelas',TRUE),
	    );

            $this->Jabatan_pelaksana_kelompok_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jabatan_pelaksana_kelompok'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jabatan_pelaksana_kelompok_model->get_by_id($id);

        if ($row) {
            $this->Jabatan_pelaksana_kelompok_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jabatan_pelaksana_kelompok'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_pelaksana_kelompok'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kelompok', 'nama kelompok', 'trim|required');
	$this->form_validation->set_rules('id_kelas', 'id kelas', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jabatan_pelaksana_kelompok.php */
/* Location: ./application/controllers/Jabatan_pelaksana_kelompok.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
