<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jabatan_kode_syarat extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Jabatan_kode_syarat_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('jabatan_kode_syarat/jabatan_kode_syarat_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Jabatan_kode_syarat_model->json();
    }

    public function read($id) 
    {
        $row = $this->Jabatan_kode_syarat_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_kode_pengangkatan' => $row->id_kode_pengangkatan,
		'isi_syarat' => $row->isi_syarat,
	    );
            $this->load->view('jabatan_kode_syarat/jabatan_kode_syarat_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_kode_syarat'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jabatan_kode_syarat/create_action'),
	    'id' => set_value('id'),
	    'id_kode_pengangkatan' => set_value('id_kode_pengangkatan'),
	    'isi_syarat' => set_value('isi_syarat'),
	);
        $this->load->view('jabatan_kode_syarat/jabatan_kode_syarat_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_kode_pengangkatan' => $this->input->post('id_kode_pengangkatan',TRUE),
		'isi_syarat' => $this->input->post('isi_syarat',TRUE),
	    );

            $this->Jabatan_kode_syarat_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jabatan_kode_syarat'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jabatan_kode_syarat_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jabatan_kode_syarat/update_action'),
		'id' => set_value('id', $row->id),
		'id_kode_pengangkatan' => set_value('id_kode_pengangkatan', $row->id_kode_pengangkatan),
		'isi_syarat' => set_value('isi_syarat', $row->isi_syarat),
	    );
            $this->load->view('jabatan_kode_syarat/jabatan_kode_syarat_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_kode_syarat'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_kode_pengangkatan' => $this->input->post('id_kode_pengangkatan',TRUE),
		'isi_syarat' => $this->input->post('isi_syarat',TRUE),
	    );

            $this->Jabatan_kode_syarat_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jabatan_kode_syarat'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jabatan_kode_syarat_model->get_by_id($id);

        if ($row) {
            $this->Jabatan_kode_syarat_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jabatan_kode_syarat'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_kode_syarat'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_kode_pengangkatan', 'id kode pengangkatan', 'trim|required');
	$this->form_validation->set_rules('isi_syarat', 'isi syarat', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jabatan_kode_syarat.php */
/* Location: ./application/controllers/Jabatan_kode_syarat.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
