<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jabatan_fungsional_angka_kredit_minimal extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Jabatan_fungsional_angka_kredit_minimal_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('jabatan_fungsional_angka_kredit_minimal/jabatan_fungsional_angka_kredit_minimal_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Jabatan_fungsional_angka_kredit_minimal_model->json();
    }

    public function read($id) 
    {
        $row = $this->Jabatan_fungsional_angka_kredit_minimal_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'angka_minimal' => $row->angka_minimal,
	    );
            $this->load->view('jabatan_fungsional_angka_kredit_minimal/jabatan_fungsional_angka_kredit_minimal_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_fungsional_angka_kredit_minimal'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jabatan_fungsional_angka_kredit_minimal/create_action'),
	    'id' => set_value('id'),
	    'angka_minimal' => set_value('angka_minimal'),
	);
        $this->load->view('jabatan_fungsional_angka_kredit_minimal/jabatan_fungsional_angka_kredit_minimal_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'angka_minimal' => $this->input->post('angka_minimal',TRUE),
	    );

            $this->Jabatan_fungsional_angka_kredit_minimal_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jabatan_fungsional_angka_kredit_minimal'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jabatan_fungsional_angka_kredit_minimal_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jabatan_fungsional_angka_kredit_minimal/update_action'),
		'id' => set_value('id', $row->id),
		'angka_minimal' => set_value('angka_minimal', $row->angka_minimal),
	    );
            $this->load->view('jabatan_fungsional_angka_kredit_minimal/jabatan_fungsional_angka_kredit_minimal_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_fungsional_angka_kredit_minimal'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'angka_minimal' => $this->input->post('angka_minimal',TRUE),
	    );

            $this->Jabatan_fungsional_angka_kredit_minimal_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jabatan_fungsional_angka_kredit_minimal'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jabatan_fungsional_angka_kredit_minimal_model->get_by_id($id);

        if ($row) {
            $this->Jabatan_fungsional_angka_kredit_minimal_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jabatan_fungsional_angka_kredit_minimal'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jabatan_fungsional_angka_kredit_minimal'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('angka_minimal', 'angka minimal', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jabatan_fungsional_angka_kredit_minimal.php */
/* Location: ./application/controllers/Jabatan_fungsional_angka_kredit_minimal.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
