<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jpendidikans extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Jpendidikans_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('jpendidikans/jpendidikans_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Jpendidikans_model->json();
    }

    public function read($id) 
    {
        $row = $this->Jpendidikans_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nama' => $row->nama,
		'level' => $row->level,
	    );
            $this->load->view('jpendidikans/jpendidikans_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jpendidikans'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('jpendidikans/create_action'),
	    'id' => set_value('id'),
	    'nama' => set_value('nama'),
	    'level' => set_value('level'),
	);
        $this->load->view('jpendidikans/jpendidikans_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'level' => $this->input->post('level',TRUE),
	    );

            $this->Jpendidikans_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('jpendidikans'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Jpendidikans_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('jpendidikans/update_action'),
		'id' => set_value('id', $row->id),
		'nama' => set_value('nama', $row->nama),
		'level' => set_value('level', $row->level),
	    );
            $this->load->view('jpendidikans/jpendidikans_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jpendidikans'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
		'level' => $this->input->post('level',TRUE),
	    );

            $this->Jpendidikans_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('jpendidikans'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Jpendidikans_model->get_by_id($id);

        if ($row) {
            $this->Jpendidikans_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('jpendidikans'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('jpendidikans'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');
	$this->form_validation->set_rules('level', 'level', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Jpendidikans.php */
/* Location: ./application/controllers/Jpendidikans.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
