<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelas extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Kelas_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('kelas/kelas_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Kelas_model->json();
    }

    public function read($id) 
    {
        $row = $this->Kelas_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'kelas' => $row->kelas,
		'nilai_bawah' => $row->nilai_bawah,
		'nilai_atas' => $row->nilai_atas,
		'id_rumpun' => $row->id_rumpun,
	    );
            $this->load->view('kelas/kelas_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelas'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kelas/create_action'),
	    'id' => set_value('id'),
	    'kelas' => set_value('kelas'),
	    'nilai_bawah' => set_value('nilai_bawah'),
	    'nilai_atas' => set_value('nilai_atas'),
	    'id_rumpun' => set_value('id_rumpun'),
	);
        $this->load->view('kelas/kelas_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'kelas' => $this->input->post('kelas',TRUE),
		'nilai_bawah' => $this->input->post('nilai_bawah',TRUE),
		'nilai_atas' => $this->input->post('nilai_atas',TRUE),
		'id_rumpun' => $this->input->post('id_rumpun',TRUE),
	    );

            $this->Kelas_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kelas'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kelas_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kelas/update_action'),
		'id' => set_value('id', $row->id),
		'kelas' => set_value('kelas', $row->kelas),
		'nilai_bawah' => set_value('nilai_bawah', $row->nilai_bawah),
		'nilai_atas' => set_value('nilai_atas', $row->nilai_atas),
		'id_rumpun' => set_value('id_rumpun', $row->id_rumpun),
	    );
            $this->load->view('kelas/kelas_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelas'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'kelas' => $this->input->post('kelas',TRUE),
		'nilai_bawah' => $this->input->post('nilai_bawah',TRUE),
		'nilai_atas' => $this->input->post('nilai_atas',TRUE),
		'id_rumpun' => $this->input->post('id_rumpun',TRUE),
	    );

            $this->Kelas_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kelas'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kelas_model->get_by_id($id);

        if ($row) {
            $this->Kelas_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kelas'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kelas'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kelas', 'kelas', 'trim|required');
	$this->form_validation->set_rules('nilai_bawah', 'nilai bawah', 'trim|required|numeric');
	$this->form_validation->set_rules('nilai_atas', 'nilai atas', 'trim|required|numeric');
	$this->form_validation->set_rules('id_rumpun', 'id rumpun', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kelas.php */
/* Location: ./application/controllers/Kelas.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
