<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Opds extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Opds_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('opds/opds_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Opds_model->json();
    }

    public function read($id) 
    {
        $row = $this->Opds_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_jenis_opd' => $row->id_jenis_opd,
		'nama_opd' => $row->nama_opd,
		'alamat' => $row->alamat,
	    );
            $this->load->view('opds/opds_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('opds'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('opds/create_action'),
	    'id' => set_value('id'),
	    'id_jenis_opd' => set_value('id_jenis_opd'),
	    'nama_opd' => set_value('nama_opd'),
	    'alamat' => set_value('alamat'),
	);
        $this->load->view('opds/opds_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_jenis_opd' => $this->input->post('id_jenis_opd',TRUE),
		'nama_opd' => $this->input->post('nama_opd',TRUE),
		'alamat' => $this->input->post('alamat',TRUE),
	    );

            $this->Opds_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('opds'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Opds_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('opds/update_action'),
		'id' => set_value('id', $row->id),
		'id_jenis_opd' => set_value('id_jenis_opd', $row->id_jenis_opd),
		'nama_opd' => set_value('nama_opd', $row->nama_opd),
		'alamat' => set_value('alamat', $row->alamat),
	    );
            $this->load->view('opds/opds_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('opds'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_jenis_opd' => $this->input->post('id_jenis_opd',TRUE),
		'nama_opd' => $this->input->post('nama_opd',TRUE),
		'alamat' => $this->input->post('alamat',TRUE),
	    );

            $this->Opds_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('opds'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Opds_model->get_by_id($id);

        if ($row) {
            $this->Opds_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('opds'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('opds'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_jenis_opd', 'id jenis opd', 'trim|required');
	$this->form_validation->set_rules('nama_opd', 'nama opd', 'trim|required');
	$this->form_validation->set_rules('alamat', 'alamat', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Opds.php */
/* Location: ./application/controllers/Opds.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
