<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Password_resets extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Password_resets_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('password_resets/password_resets_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Password_resets_model->json();
    }

    public function read($id) 
    {
        $row = $this->Password_resets_model->get_by_id($id);
        if ($row) {
            $data = array(
		'nohp' => $row->nohp,
		'token' => $row->token,
	    );
            $this->load->view('password_resets/password_resets_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('password_resets'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('password_resets/create_action'),
	    'nohp' => set_value('nohp'),
	    'token' => set_value('token'),
	);
        $this->load->view('password_resets/password_resets_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nohp' => $this->input->post('nohp',TRUE),
		'token' => $this->input->post('token',TRUE),
	    );

            $this->Password_resets_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('password_resets'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Password_resets_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('password_resets/update_action'),
		'nohp' => set_value('nohp', $row->nohp),
		'token' => set_value('token', $row->token),
	    );
            $this->load->view('password_resets/password_resets_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('password_resets'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'nohp' => $this->input->post('nohp',TRUE),
		'token' => $this->input->post('token',TRUE),
	    );

            $this->Password_resets_model->update($this->input->post('', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('password_resets'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Password_resets_model->get_by_id($id);

        if ($row) {
            $this->Password_resets_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('password_resets'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('password_resets'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nohp', 'nohp', 'trim|required');
	$this->form_validation->set_rules('token', 'token', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Password_resets.php */
/* Location: ./application/controllers/Password_resets.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
