<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pegawai_pendidikans extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Pegawai_pendidikans_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('pegawai_pendidikans/pegawai_pendidikans_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pegawai_pendidikans_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pegawai_pendidikans_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'pegawai_id' => $row->pegawai_id,
		'jpendidikan_id' => $row->jpendidikan_id,
		'jurusan_id' => $row->jurusan_id,
	    );
            $this->load->view('pegawai_pendidikans/pegawai_pendidikans_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawai_pendidikans'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pegawai_pendidikans/create_action'),
	    'id' => set_value('id'),
	    'pegawai_id' => set_value('pegawai_id'),
	    'jpendidikan_id' => set_value('jpendidikan_id'),
	    'jurusan_id' => set_value('jurusan_id'),
	);
        $this->load->view('pegawai_pendidikans/pegawai_pendidikans_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'pegawai_id' => $this->input->post('pegawai_id',TRUE),
		'jpendidikan_id' => $this->input->post('jpendidikan_id',TRUE),
		'jurusan_id' => $this->input->post('jurusan_id',TRUE),
	    );

            $this->Pegawai_pendidikans_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pegawai_pendidikans'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pegawai_pendidikans_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pegawai_pendidikans/update_action'),
		'id' => set_value('id', $row->id),
		'pegawai_id' => set_value('pegawai_id', $row->pegawai_id),
		'jpendidikan_id' => set_value('jpendidikan_id', $row->jpendidikan_id),
		'jurusan_id' => set_value('jurusan_id', $row->jurusan_id),
	    );
            $this->load->view('pegawai_pendidikans/pegawai_pendidikans_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawai_pendidikans'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'pegawai_id' => $this->input->post('pegawai_id',TRUE),
		'jpendidikan_id' => $this->input->post('jpendidikan_id',TRUE),
		'jurusan_id' => $this->input->post('jurusan_id',TRUE),
	    );

            $this->Pegawai_pendidikans_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pegawai_pendidikans'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pegawai_pendidikans_model->get_by_id($id);

        if ($row) {
            $this->Pegawai_pendidikans_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pegawai_pendidikans'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawai_pendidikans'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('pegawai_id', 'pegawai id', 'trim|required');
	$this->form_validation->set_rules('jpendidikan_id', 'jpendidikan id', 'trim|required');
	$this->form_validation->set_rules('jurusan_id', 'jurusan id', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pegawai_pendidikans.php */
/* Location: ./application/controllers/Pegawai_pendidikans.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
