<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pegawais extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Pegawais_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('pegawais/pegawais_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pegawais_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pegawais_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nip' => $row->nip,
		'nama' => $row->nama,
		'email' => $row->email,
		'password' => $row->password,
	    );
            $this->load->view('pegawais/pegawais_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawais'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pegawais/create_action'),
	    'id' => set_value('id'),
	    'nip' => set_value('nip'),
	    'nama' => set_value('nama'),
	    'email' => set_value('email'),
	    'password' => set_value('password'),
	);
        $this->load->view('pegawais/pegawais_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nip' => $this->input->post('nip',TRUE),
		'nama' => $this->input->post('nama',TRUE),
		'email' => $this->input->post('email',TRUE),
		'password' => $this->input->post('password',TRUE),
	    );

            $this->Pegawais_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pegawais'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pegawais_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pegawais/update_action'),
		'id' => set_value('id', $row->id),
		'nip' => set_value('nip', $row->nip),
		'nama' => set_value('nama', $row->nama),
		'email' => set_value('email', $row->email),
		'password' => set_value('password', $row->password),
	    );
            $this->load->view('pegawais/pegawais_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawais'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nip' => $this->input->post('nip',TRUE),
		'nama' => $this->input->post('nama',TRUE),
		'email' => $this->input->post('email',TRUE),
		'password' => $this->input->post('password',TRUE),
	    );

            $this->Pegawais_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pegawais'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pegawais_model->get_by_id($id);

        if ($row) {
            $this->Pegawais_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pegawais'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pegawais'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nip', 'nip', 'trim|required');
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');
	$this->form_validation->set_rules('email', 'email', 'trim|required');
	$this->form_validation->set_rules('password', 'password', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pegawais.php */
/* Location: ./application/controllers/Pegawais.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
