<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pma__bookmark extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Pma__bookmark_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('pma__bookmark/pma__bookmark_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pma__bookmark_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pma__bookmark_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'dbase' => $row->dbase,
		'user' => $row->user,
		'label' => $row->label,
		'query' => $row->query,
	    );
            $this->load->view('pma__bookmark/pma__bookmark_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__bookmark'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pma__bookmark/create_action'),
	    'id' => set_value('id'),
	    'dbase' => set_value('dbase'),
	    'user' => set_value('user'),
	    'label' => set_value('label'),
	    'query' => set_value('query'),
	);
        $this->load->view('pma__bookmark/pma__bookmark_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'dbase' => $this->input->post('dbase',TRUE),
		'user' => $this->input->post('user',TRUE),
		'label' => $this->input->post('label',TRUE),
		'query' => $this->input->post('query',TRUE),
	    );

            $this->Pma__bookmark_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pma__bookmark'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pma__bookmark_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pma__bookmark/update_action'),
		'id' => set_value('id', $row->id),
		'dbase' => set_value('dbase', $row->dbase),
		'user' => set_value('user', $row->user),
		'label' => set_value('label', $row->label),
		'query' => set_value('query', $row->query),
	    );
            $this->load->view('pma__bookmark/pma__bookmark_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__bookmark'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'dbase' => $this->input->post('dbase',TRUE),
		'user' => $this->input->post('user',TRUE),
		'label' => $this->input->post('label',TRUE),
		'query' => $this->input->post('query',TRUE),
	    );

            $this->Pma__bookmark_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pma__bookmark'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pma__bookmark_model->get_by_id($id);

        if ($row) {
            $this->Pma__bookmark_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pma__bookmark'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__bookmark'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('dbase', 'dbase', 'trim|required');
	$this->form_validation->set_rules('user', 'user', 'trim|required');
	$this->form_validation->set_rules('label', 'label', 'trim|required');
	$this->form_validation->set_rules('query', 'query', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pma__bookmark.php */
/* Location: ./application/controllers/Pma__bookmark.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
