<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pma__navigationhiding extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Pma__navigationhiding_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('pma__navigationhiding/pma__navigationhiding_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pma__navigationhiding_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pma__navigationhiding_model->get_by_id($id);
        if ($row) {
            $data = array(
		'username' => $row->username,
		'item_name' => $row->item_name,
		'item_type' => $row->item_type,
		'db_name' => $row->db_name,
		'table_name' => $row->table_name,
	    );
            $this->load->view('pma__navigationhiding/pma__navigationhiding_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__navigationhiding'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pma__navigationhiding/create_action'),
	    'username' => set_value('username'),
	    'item_name' => set_value('item_name'),
	    'item_type' => set_value('item_type'),
	    'db_name' => set_value('db_name'),
	    'table_name' => set_value('table_name'),
	);
        $this->load->view('pma__navigationhiding/pma__navigationhiding_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Pma__navigationhiding_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pma__navigationhiding'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pma__navigationhiding_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pma__navigationhiding/update_action'),
		'username' => set_value('username', $row->username),
		'item_name' => set_value('item_name', $row->item_name),
		'item_type' => set_value('item_type', $row->item_type),
		'db_name' => set_value('db_name', $row->db_name),
		'table_name' => set_value('table_name', $row->table_name),
	    );
            $this->load->view('pma__navigationhiding/pma__navigationhiding_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__navigationhiding'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('username', TRUE));
        } else {
            $data = array(
	    );

            $this->Pma__navigationhiding_model->update($this->input->post('username', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pma__navigationhiding'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pma__navigationhiding_model->get_by_id($id);

        if ($row) {
            $this->Pma__navigationhiding_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pma__navigationhiding'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__navigationhiding'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('username', 'username', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pma__navigationhiding.php */
/* Location: ./application/controllers/Pma__navigationhiding.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
