<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pma__pdf_pages extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Pma__pdf_pages_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('pma__pdf_pages/pma__pdf_pages_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pma__pdf_pages_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pma__pdf_pages_model->get_by_id($id);
        if ($row) {
            $data = array(
		'db_name' => $row->db_name,
		'page_nr' => $row->page_nr,
		'page_descr' => $row->page_descr,
	    );
            $this->load->view('pma__pdf_pages/pma__pdf_pages_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__pdf_pages'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pma__pdf_pages/create_action'),
	    'db_name' => set_value('db_name'),
	    'page_nr' => set_value('page_nr'),
	    'page_descr' => set_value('page_descr'),
	);
        $this->load->view('pma__pdf_pages/pma__pdf_pages_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'db_name' => $this->input->post('db_name',TRUE),
		'page_descr' => $this->input->post('page_descr',TRUE),
	    );

            $this->Pma__pdf_pages_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pma__pdf_pages'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pma__pdf_pages_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pma__pdf_pages/update_action'),
		'db_name' => set_value('db_name', $row->db_name),
		'page_nr' => set_value('page_nr', $row->page_nr),
		'page_descr' => set_value('page_descr', $row->page_descr),
	    );
            $this->load->view('pma__pdf_pages/pma__pdf_pages_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__pdf_pages'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('page_nr', TRUE));
        } else {
            $data = array(
		'db_name' => $this->input->post('db_name',TRUE),
		'page_descr' => $this->input->post('page_descr',TRUE),
	    );

            $this->Pma__pdf_pages_model->update($this->input->post('page_nr', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pma__pdf_pages'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pma__pdf_pages_model->get_by_id($id);

        if ($row) {
            $this->Pma__pdf_pages_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pma__pdf_pages'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__pdf_pages'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('db_name', 'db name', 'trim|required');
	$this->form_validation->set_rules('page_descr', 'page descr', 'trim|required');

	$this->form_validation->set_rules('page_nr', 'page_nr', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pma__pdf_pages.php */
/* Location: ./application/controllers/Pma__pdf_pages.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
