<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pma__usergroups extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Pma__usergroups_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('pma__usergroups/pma__usergroups_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pma__usergroups_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pma__usergroups_model->get_by_id($id);
        if ($row) {
            $data = array(
		'usergroup' => $row->usergroup,
		'tab' => $row->tab,
		'allowed' => $row->allowed,
	    );
            $this->load->view('pma__usergroups/pma__usergroups_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__usergroups'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pma__usergroups/create_action'),
	    'usergroup' => set_value('usergroup'),
	    'tab' => set_value('tab'),
	    'allowed' => set_value('allowed'),
	);
        $this->load->view('pma__usergroups/pma__usergroups_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Pma__usergroups_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pma__usergroups'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pma__usergroups_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pma__usergroups/update_action'),
		'usergroup' => set_value('usergroup', $row->usergroup),
		'tab' => set_value('tab', $row->tab),
		'allowed' => set_value('allowed', $row->allowed),
	    );
            $this->load->view('pma__usergroups/pma__usergroups_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__usergroups'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('usergroup', TRUE));
        } else {
            $data = array(
	    );

            $this->Pma__usergroups_model->update($this->input->post('usergroup', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pma__usergroups'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pma__usergroups_model->get_by_id($id);

        if ($row) {
            $this->Pma__usergroups_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pma__usergroups'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__usergroups'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('usergroup', 'usergroup', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pma__usergroups.php */
/* Location: ./application/controllers/Pma__usergroups.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
