<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pma__users extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Pma__users_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('pma__users/pma__users_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pma__users_model->json();
    }

    public function read($id) 
    {
        $row = $this->Pma__users_model->get_by_id($id);
        if ($row) {
            $data = array(
		'username' => $row->username,
		'usergroup' => $row->usergroup,
	    );
            $this->load->view('pma__users/pma__users_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__users'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('pma__users/create_action'),
	    'username' => set_value('username'),
	    'usergroup' => set_value('usergroup'),
	);
        $this->load->view('pma__users/pma__users_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Pma__users_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('pma__users'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pma__users_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('pma__users/update_action'),
		'username' => set_value('username', $row->username),
		'usergroup' => set_value('usergroup', $row->usergroup),
	    );
            $this->load->view('pma__users/pma__users_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__users'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('username', TRUE));
        } else {
            $data = array(
	    );

            $this->Pma__users_model->update($this->input->post('username', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pma__users'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pma__users_model->get_by_id($id);

        if ($row) {
            $this->Pma__users_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pma__users'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pma__users'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('username', 'username', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Pma__users.php */
/* Location: ./application/controllers/Pma__users.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/
