<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jabatans_model extends CI_Model
{

    public $table = 'jabatans';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,id_urusan,id_jabatan_level,kode_jabatan,nama_jabatan,jenis,tugas_jabatan,id_rumpun,id_jenjang,opd_id,status,kode_pengangkatan');
        $this->datatables->from('jabatans');
        //add this line for join
        //$this->datatables->join('table2', 'jabatans.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jabatans/update/$1'),'<i class="fa fa-pencil"></i>','class="btn btn-warning btn-xs"' )." ".anchor(site_url('jabatans/delete/$1'),'<i class="fa fa-trash"></i>','class="btn btn-danger btn-xs" onclick="javasciprt: return confirm(\'Apakah Anda Yakin Menghapus Data Ini ?\')"'), 'id');
        return $this->datatables->generate();
    }
    // datatables
    function json_jabatan_struktural($id='') {
        
        if($id==''){
            $this->db->select('jabatans.id,nama_jabatan,nama_opd');
        //add this line for join
        $this->db->where('jabatans.jenis',1);
        $this->db->join('opds','opds.id=jabatans.opd_id');
        }else{
            $this->db->select('jabatans.id,nama_jabatan,nama_opd');
        $this->db->where('jabatans.jenis',1);
        $this->db->where('jabatans.opd_id',$id);
        //add this line for join
        $this->db->join('opds','opds.id=jabatans.opd_id');
        }
        
        return $this->db->get($this->table)->result();
    }
    function json_jabatan_master($id='') {
        
        if($id==''){
            $this->db->join('urusan','urusan.id=jabatans.id_urusan');
                     $this->db->where('jabatans.status',null);
                     $this->db->select('jabatans.id as id, urusan.nama_urusan as nama_urusan,jabatans.nama_jabatan as nama_jabatan,jabatans.tugas_jabatan as tugas_jabatan');
        }else{
            $this->db->join('urusan','urusan.id=jabatans.id_urusan');
                     $this->db->where('jabatans.id_urusan',$id);
                     $this->db->where('jabatans.status',null);
                     $this->db->select('jabatans.id as id, urusan.nama_urusan as nama_urusan,jabatans.nama_jabatan as nama_jabatan,jabatans.tugas_jabatan as tugas_jabatan');
        }
        
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_urusan', $q);
	$this->db->or_like('id_jabatan_level', $q);
	$this->db->or_like('kode_jabatan', $q);
	$this->db->or_like('nama_jabatan', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('tugas_jabatan', $q);
	$this->db->or_like('id_rumpun', $q);
	$this->db->or_like('id_jenjang', $q);
	$this->db->or_like('opd_id', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('kode_pengangkatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_urusan', $q);
	$this->db->or_like('id_jabatan_level', $q);
	$this->db->or_like('kode_jabatan', $q);
	$this->db->or_like('nama_jabatan', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('tugas_jabatan', $q);
	$this->db->or_like('id_rumpun', $q);
	$this->db->or_like('id_jenjang', $q);
	$this->db->or_like('opd_id', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('kode_pengangkatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jabatans.php */
/* Location: ./application/controllers/Jabatans.php */
/* Please DO NOT modify this information : */
/* Generated by mahrus@pcr.ac.id*/